name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  action-in-development:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: buld-demo
      run: cd demo && npm install && npm run build && cd ..
    - name: ls
      run: pwd && ls -a
    - name: package install
      run: npm ci
    - name: origina-workflow
      uses: ./
      with:
        milliseconds: 1000
        configPath: "/demo/webpack.config"
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /analyzeOutputs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
