name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm ci

  # test action works running from the graph
  action-in-development:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
